version: "3.7"

services:
  autobrr:
    container_name: autobrr
    image: ghcr.io/autobrr/autobrr:latest
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - PUID=1000
      - PGID=1000
    user: 1000:1000
    volumes:
      - /config/autobrr:/config
    ports:
      - 7474:7474