version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:  
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - JELLYFIN_PublishedServerUrl=192.168.50.54 #optional
    volumes:
      - /config/jellyfin:/config
      - /volume4:/volume4
      - /volume5:/volume5
      - /EXT4T:/EXT4T
      - /EXT5T:/EXT5T
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
