version: "2.1"
services:
  lidarr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /config/overseerr:/config
      - /media/joe/volume4:/volume4
      - /media/joe/volume5:/volume5
      - /media/joe/EXT4T:/volume6
      - /media/joe/EXT5T:/volume7
    ports:
      - 5055:5055
    restart: unless-stopped