services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    cap_add:
      - NET_ADMIN
    volumes:
      - /config/qbittorrent:/config
      - /volume4:/volume4
      - /volume5:/volume5
      - /EXT4T:/EXT4T
      - /EXT5T:/EXT5T
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=9191
      - TORRENTING_PORT=6881
    devices:
      - /dev/net/tun
    network_mode: "container:gluetun-gluetun-1"
    #ports:
    #  - 9191:9191
    #  - 6881:6881
    #  - 6881:6881/udp
    restart: unless-stopped
  