version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /config/radarr:/config
      - /volume4:/volume4
      - /volume5:/volume5
      - /volume6:/volume6
      - /volume7:/volume7
    ports:
      - 7878:7878
    restart: unless-stopped


    # admin/admin123