version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /config/radarr:/config
      - /media/joe/volume4:/volume4
      - /media/joe/volume5:/volume5
      - /media/joe/EXT4T:/volume6
      - /media/joe/EXT5T:/volume7
    ports:
      - 7878:7878
    restart: unless-stopped