version: "2.1"
services:
  sabnzbd:
      image: lscr.io/linuxserver/sabnzbd:latest
      container_name: sabnzbd
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/New_York
      volumes:
        - /config/sabnzbd:/config
        - /volume4:/volume4
        - /volume5:/volume5
        - /EXT4T:/EXT4T
        - /EXT5T:/EXT5T
      ports:
        - 8080:8080
      restart: unless-stopped