version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /config/sonarr:/config
      - /volume4:/volume4
      - /volume5:/volume5
      - /volume6:/volume6
      - /volume7:/volume7
    ports:
      - 8989:8989
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped

#admin/admin123