version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /config/radarr:/config
      - /media/joe/volume4:/volume4
      - /media/joe/volume5:/volume5
      - /media/joe/EXT4T:/volume6
      - /media/joe/EXT5T:/volume7
    ports:
      - 8989:8989
    restart: unless-stopped