version: "2.1"
services:
  transmission-openvpn:
    image: haugene/transmission-openvpn:latest
    cap_add:
      - NET_ADMIN
    volumes:
      - /config/transmission:/config
      - /volume4:/volume4
      - /volume5:/volume5
      - /EXT4T:/EXT4T
      - /EXT5T:/EXT5T
    container_name: transmission-openvpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_CONFIG=mexico
      - OPENVPN_USERNAME=************USE TOKEN******************
      - OPENVPN_PASSWORD=************USE TOKEN******************
      - NORDVPN_COUNTRY=MX
      - NORDVPN_CATEGORY=P2P
      - NORDVPN_PROTOCOL=udp
      # cidr notation for local network
      - LOCAL_NETWORK=192.168.0.0/13
      # settings in app dont seem to work
      - TRANSMISSION_DOWNLOAD_DIR=/volume4/completed
      - TRANSMISSION_INCOMPLETE_DIR=/volume4/incomplete
      - TRANSMISSION_WATCH_DIR=/volume4/watch
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - 9091:9091
    restart: unless-stopped      
    